---
development:
  cloud_name: hihvgdv7h
  api_key: '992396865787656'
  api_secret: u3n0pQ9a_4Hm7X7-uQ01k5z9Aok
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hihvgdv7h
  api_key: '992396865787656'
  api_secret: u3n0pQ9a_4Hm7X7-uQ01k5z9Aok
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hihvgdv7h
  api_key: '992396865787656'
  api_secret: u3n0pQ9a_4Hm7X7-uQ01k5z9Aok
  enhance_image_tag: true
  static_image_support: false
